### ISSUE TITLE
Installation failed due to composer

### ISSUE THREAD

**Issue by utzer** [YunoHost-Apps/movim_ynh#32]
### Describe the bug

The installation failed because of
```
2021-09-08 22:24:40,968: WARNING -   [RuntimeException]
2021-09-08 22:24:40,969: WARNING -   The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly
```
I guess, but there is a [log](https://paste.yunohost.org/raw/fuzetubohi). 

### Context

- Hardware: some small box
- YunoHost version: 4.2.8.2
- I have access to my server: SSH and web interface 
- Using, or trying to install package version/branch: stabel movim, just via webinterface. /yunohost/admin... 

### Logs

[log](https://paste.yunohost.org/raw/fuzetubohi)

**Comment by ticktostick** [comment]
Same problem here

**Comment by utkarshsethi** [comment]
Adding my logs too: [logs](https://paste.yunohost.org/raw/abotokapun)
