### ISSUE TITLE
Login page endless reload

### ISSUE THREAD

**Issue by Emilien-Etadam** [YunoHost-Apps/movim_ynh#46]
### Describe the bug

Login page is reloading until the service stop on a first install of Movim. I can access to admin page without any problem.

### Context

- Hardware: Raspberry Pi 4 ARM64
- YunoHost version:  11.0.9.14
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version : last version available in yunohost

![waterfox_bsN0u2Ot0I](https://user-images.githubusercontent.com/56485277/188920237-74038708-3f9b-4042-9c1e-80cfa63b8251.gif)

Logs : https://paste.yunohost.org/umokijosur

**Comment by Salamandar** [comment]
Fixed.
