### ISSUE TITLE
Movim v0.20 available

### ISSUE THREAD

**Issue by anubister** [YunoHost-Apps/movim_ynh#47]
Hi,
a kind reminder that a new version (v0.20) is available : https://github.com/movim/movim/tree/v0.20
could you update the package ?
Many thanks !

**Comment by silverhook** [comment]
Movim 0.23 is out by now already:

https://github.com/movim/movim/releases/tag/v0.23

Since 0.20 the installation instructions moved to: https://github.com/movim/movim/blob/master/INSTALL.md

**Comment by OniriCorpe** [comment]
Should be upgraded soon ^w^

**Comment by silverhook** [comment]
yay! ^ω^
