### ISSUE TITLE
domain? Pod? Server? SSO? LDAP? VoIP? OMEMO

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/movim_ynh#5]
Hello,

When I'm reading the readme.md, there are few things I don't understand.
Is this package using the yunohost XMPP server (metronome if I'm right)? Does yunohost become a movim pod then? or is it just installing a web client? Does it support the yunohost SSO and LDAP feature?

To be specific, taking a mydomainname.dd as the main domaine name of yunohost, if movim is installed on movim.mydomainname.dd, will Jack and Jane who already are registered on mydomainname.dd and have email like jack@mydomainname.dd and jane@mydomainname.dd, will be able to use movim clicking on movim tile of yunohost without entering any id and password and will they be able to share jack@mydomainname.dd and jane@mydomainname.dd as their movim (XMPP) account without any further work?

Is it possible to use VoIP?
Will OMEMO be implemented when Movim 0.15 will be released as explained here, https://github.com/movim/movim/issues/63 ?

**Comment by ImaCrea** [comment]
+1

**Comment by anubister** [comment]
> When I'm reading the readme.md, there are few things I don't understand.
> Is this package using the yunohost XMPP server (metronome if I'm right)? 

Yes

> Does yunohost become a movim pod then? 

Yes

> To be specific, taking a mydomainname.dd as the main domaine name of yunohost, if movim is installed on movim.mydomainname.dd, will Jack and Jane who already are registered on mydomainname.dd and have email like [jack@mydomainname.dd](mailto:jack@mydomainname.dd) and [jane@mydomainname.dd](mailto:jane@mydomainname.dd), will be able to use movim clicking on movim tile of yunohost without entering any id and password and will they be able to share [jack@mydomainname.dd](mailto:jack@mydomainname.dd) and [jane@mydomainname.dd](mailto:jane@mydomainname.dd) as their movim (XMPP) account without any further work?

I'm not sure whether SSO is (currently) working with this app... to be checked.

> Is it possible to use VoIP?

Yes, but currently a manual procedure need to be done : see https://github.com/YunoHost/issues/issues/1607

> Will OMEMO be implemented when Movim 0.15 will be released as explained here, [movim/movim#63](https://github.com/movim/movim/issues/63) ?

This feature has been delayed; a bounty is proposed so you can offer some money if you want it sooner.

**Comment by alexAubin** [comment]
Closing as questions got answered in previous comment
