### ISSUE TITLE
0.23 on Yunohost 12 does not work better

### ISSUE THREAD

**Issue by anubister** [YunoHost-Apps/movim_ynh#61]
### Describe the bug

When installed on a dedicated subdomain : automatically redirects to https://domain/news with error 404 
When installed on a subpath : it does not connect
in both case in Nginx logs : `[error] 94545#94545: *4708 open() "/usr/share/nginx/htmlindex.php" failed (2: No such file or directory)`

it seems there is at least a "/" missing in the path of some configuration file?

### Context

- YunoHost version: 12.0.0+202403202245
- Using, or trying to install package version/branch: ci-auto-update-0.23

### Steps to reproduce

Connect to the domain freshly configured

### Expected behavior

Access Movim

### Logs
feel free to ask for more logs, dedicated tests...

**Comment by Salamandar** [comment]
This should be fixed with the last merge on master.
